### ISSUE TITLE
Screenshots should have a transparent background

### ISSUE THREAD

**Issue by danrabbit** [brandonlujan/exchange#5]
Hey thanks for submitting your app in AppCenter Dashboard! While reviewing I noticed that your screenshot doesn't use a transparent background. You should take a screenshot of your app using "Grab the current window" with the built-in screenshot tool.

For you're convenience, here's one I took:

![screenshot from 2017-06-17 20 23 11](https://user-images.githubusercontent.com/7277719/27257824-d6534dd4-539a-11e7-8961-4da5546c5529.png)

**Comment by brandonlujan** [comment]
Thanks, fixed in commit #3a16b4e
