### ISSUE TITLE
PPA

### ISSUE THREAD

**Issue by giovannicaligaris** [brandonlujan/exchange#9]
I tried the app on Elementary and it is really cool. Is it possible to have a ppa so it can be installed in other Ubuntu distros or at least a deb file?

**Comment by peteruithoven** [comment]
https://github.com/mh-cbon/go-github-release/issues/6

**Comment by brandonlujan** [comment]
Right now my priority is adding everything that's on my mind to the app, but I would love if someone would make a ppa for this app, althought I can't guarantee that it's gonna work :T I'm just learning

**Comment by brandonlujan** [comment]
Marked as wontfix, if anyone is interested give it a shot!
